import { defineConfig, devices } from "@playwright/test"

/**
 * Playwright config for impactx-ui showcase visual regression + a11y gate.
 *
 * Runs in 3 viewports (mobile / tablet / desktop) against the apps/web
 * showcase routes. Screenshots + axe-core violations are diffed against
 * committed baselines.
 *
 * IMPORTANT: baselines committed to git were generated by the bot during
 * overnight execution. They are "what was built" not "what is correct".
 * Rafa should eyeball-approve them before merging this branch.
 */
export default defineConfig({
  testDir: "./playwright-tests",
  fullyParallel: true,
  forbidOnly: !!process.env["CI"],
  retries: process.env["CI"] ? 2 : 0,
  workers: process.env["CI"] ? 1 : undefined,
  reporter: process.env["CI"] ? "github" : "list",

  timeout: 60_000,

  use: {
    baseURL: "http://localhost:3002",
    trace: "on-first-retry",
    navigationTimeout: 45_000,
  },

  // Tolerance for pixel diffs (some font rendering varies across OS).
  expect: {
    toHaveScreenshot: {
      maxDiffPixelRatio: 0.02,
      threshold: 0.2,
    },
  },

  // Chromium-only across all viewports — avoids needing WebKit install in CI
  // and on dev machines. Visual diffs are the goal, not cross-browser parity.
  projects: [
    {
      name: "mobile",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 375, height: 667 },
      },
    },
    {
      name: "tablet",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 768, height: 1024 },
      },
    },
    {
      name: "desktop",
      use: { ...devices["Desktop Chrome"], viewport: { width: 1440, height: 900 } },
    },
  ],

  webServer: {
    command: "pnpm dev",
    url: "http://localhost:3002",
    reuseExistingServer: !process.env["CI"],
    timeout: 120_000,
  },
})
