import { defineConfig, devices } from "@playwright/test"

/**
 * Playwright config for impactx-ui showcase visual regression + a11y gate.
 *
 * Runs in 3 viewports (mobile / tablet / desktop) against the apps/web
 * showcase routes. Screenshots + axe-core violations are diffed against
 * committed baselines.
 *
 * IMPORTANT: baselines committed to git were generated by the bot during
 * overnight execution. They are "what was built" not "what is correct".
 * Rafa should eyeball-approve them before merging this branch.
 */
export default defineConfig({
  testDir: "./playwright-tests",
  fullyParallel: false,
  forbidOnly: !!process.env["CI"],
  retries: 1,
  // 2 workers parallel — balances dev server load against speed.
  // 1 was too slow (~5min), unlimited overloaded Next dev compile.
  workers: 2,
  reporter: process.env["CI"] ? "github" : "list",

  timeout: 120_000,

  use: {
    baseURL: "http://localhost:3002",
    trace: "on-first-retry",
    navigationTimeout: 60_000,
    actionTimeout: 30_000,
  },

  // Snapshots compartilhados entre darwin/linux/win — mantém {projectName}
  // (viewport: mobile/tablet/desktop) mas remove sufixo de OS. Tolerância de
  // pixel diff (maxDiffPixelRatio/threshold) absorve antialiasing entre OSes.
  snapshotPathTemplate:
    "{snapshotDir}/{testFileDir}/{testFileName}-snapshots/{arg}-{projectName}{ext}",
  expect: {
    toHaveScreenshot: {
      // 5% tolerance — accommodates cross-OS antialiasing (darwin↔linux ~3%)
      maxDiffPixelRatio: 0.05,
      threshold: 0.3,
    },
  },

  // Chromium-only across all viewports — avoids needing WebKit install in CI
  // and on dev machines. Visual diffs are the goal, not cross-browser parity.
  projects: [
    {
      name: "mobile",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 375, height: 667 },
      },
    },
    {
      name: "tablet",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 768, height: 1024 },
      },
    },
    {
      name: "desktop",
      use: { ...devices["Desktop Chrome"], viewport: { width: 1440, height: 900 } },
    },
  ],

  webServer: {
    command: "pnpm dev",
    url: "http://localhost:3002",
    reuseExistingServer: !process.env["CI"],
    timeout: 180_000,
  },
})
